'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SyncSetting_ActiveCaption_Sync() As Boolean
            Get
                Return CType(Me("SyncSetting_ActiveCaption_Sync"),Boolean)
            End Get
            Set
                Me("SyncSetting_ActiveCaption_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SyncSetting_ActiveCaption_SetBrit() As Boolean
            Get
                Return CType(Me("SyncSetting_ActiveCaption_SetBrit"),Boolean)
            End Get
            Set
                Me("SyncSetting_ActiveCaption_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property SyncSetting_ActiveCaption_UsrBrit() As Double
            Get
                Return CType(Me("SyncSetting_ActiveCaption_UsrBrit"),Double)
            End Get
            Set
                Me("SyncSetting_ActiveCaption_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SyncSetting_GradientActiveCaption_Sync() As Boolean
            Get
                Return CType(Me("SyncSetting_GradientActiveCaption_Sync"),Boolean)
            End Get
            Set
                Me("SyncSetting_GradientActiveCaption_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SyncSetting_GradientActiveCaption_SetBrit() As Boolean
            Get
                Return CType(Me("SyncSetting_GradientActiveCaption_SetBrit"),Boolean)
            End Get
            Set
                Me("SyncSetting_GradientActiveCaption_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.7")>  _
        Public Property SyncSetting_GradientActiveCaption_UsrBrit() As Double
            Get
                Return CType(Me("SyncSetting_GradientActiveCaption_UsrBrit"),Double)
            End Get
            Set
                Me("SyncSetting_GradientActiveCaption_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SyncSetting_Highlight_Sync() As Boolean
            Get
                Return CType(Me("SyncSetting_Highlight_Sync"),Boolean)
            End Get
            Set
                Me("SyncSetting_Highlight_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SyncSetting_Highlight_SetBrit() As Boolean
            Get
                Return CType(Me("SyncSetting_Highlight_SetBrit"),Boolean)
            End Get
            Set
                Me("SyncSetting_Highlight_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property SyncSetting_Highlight_UsrBrit() As Double
            Get
                Return CType(Me("SyncSetting_Highlight_UsrBrit"),Double)
            End Get
            Set
                Me("SyncSetting_Highlight_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SyncSetting_MenuHighlight_Sync() As Boolean
            Get
                Return CType(Me("SyncSetting_MenuHighlight_Sync"),Boolean)
            End Get
            Set
                Me("SyncSetting_MenuHighlight_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SyncSetting_MenuHighlight_SetBrit() As Boolean
            Get
                Return CType(Me("SyncSetting_MenuHighlight_SetBrit"),Boolean)
            End Get
            Set
                Me("SyncSetting_MenuHighlight_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property SyncSetting_MenuHighlight_UsrBrit() As Double
            Get
                Return CType(Me("SyncSetting_MenuHighlight_UsrBrit"),Double)
            End Get
            Set
                Me("SyncSetting_MenuHighlight_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SyncSetting_HotTrack_Sync() As Boolean
            Get
                Return CType(Me("SyncSetting_HotTrack_Sync"),Boolean)
            End Get
            Set
                Me("SyncSetting_HotTrack_Sync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SyncSetting_HotTrack_SetBrit() As Boolean
            Get
                Return CType(Me("SyncSetting_HotTrack_SetBrit"),Boolean)
            End Get
            Set
                Me("SyncSetting_HotTrack_SetBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property SyncSetting_HotTrack_UsrBrit() As Double
            Get
                Return CType(Me("SyncSetting_HotTrack_UsrBrit"),Double)
            End Get
            Set
                Me("SyncSetting_HotTrack_UsrBrit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AccentPalette")>  _
        Public Property General_AccentSource() As Global.AccentCS.Helpers.AccentSources
            Get
                Return CType(Me("General_AccentSource"),Global.AccentCS.Helpers.AccentSources)
            End Get
            Set
                Me("General_AccentSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property UI_ContextMenuStyle() As Integer
            Get
                Return CType(Me("UI_ContextMenuStyle"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property General_InstantOptionChanges() As Boolean
            Get
                Return CType(Me("General_InstantOptionChanges"),Boolean)
            End Get
            Set
                Me("General_InstantOptionChanges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ForeSysColorUsrValue_ActiveCaptionText() As Global.System.Drawing.Color
            Get
                Return CType(Me("ForeSysColorUsrValue_ActiveCaptionText"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ForeSysColorUsrValue_ActiveCaptionText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ForeSysColorUsrValue_HighlightText() As Global.System.Drawing.Color
            Get
                Return CType(Me("ForeSysColorUsrValue_HighlightText"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ForeSysColorUsrValue_HighlightText") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AccentCS.App.My.MySettings
            Get
                Return Global.AccentCS.App.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
