'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizedResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AccentCS.App.LocalizedResources", GetType(LocalizedResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click for more options.
        '''</summary>
        Friend Shared ReadOnly Property Caption_ClickForMoreOptions() As String
            Get
                Return ResourceManager.GetString("Caption_ClickForMoreOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to change which variant
        '''of the system accent is used
        '''as the base accent color.
        '''</summary>
        Friend Shared ReadOnly Property Caption_ClickToChangeAccentSource() As String
            Get
                Return ResourceManager.GetString("Caption_ClickToChangeAccentSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current RGB value:.
        '''</summary>
        Friend Shared ReadOnly Property Caption_CurrentRGBValue() As String
            Get
                Return ResourceManager.GetString("Caption_CurrentRGBValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The accent color is invalid. You can try to fix this issue by changing the Accent source option in the application options..
        '''</summary>
        Friend Shared ReadOnly Property Error_InvalidAccent() As String
            Get
                Return ResourceManager.GetString("Error_InvalidAccent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid color.
        '''</summary>
        Friend Shared ReadOnly Property Error_InvalidColor() As String
            Get
                Return ResourceManager.GetString("Error_InvalidColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The last synchronization attemp failed.
        '''</summary>
        Friend Shared ReadOnly Property ErrorIntro_LastSyncAttempFailed() As String
            Get
                Return ResourceManager.GetString("ErrorIntro_LastSyncAttempFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Another instance of {0} is already running. If you can&apos;t find it, it may be hidden in the notification area..
        '''</summary>
        Friend Shared ReadOnly Property Info_ExistingAppInstance() As String
            Get
                Return ResourceManager.GetString("Info_ExistingAppInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System colors successfully restored to defaults..
        '''</summary>
        Friend Shared ReadOnly Property Info_ThemeResetSuccess() As String
            Get
                Return ResourceManager.GetString("Info_ThemeResetSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to •You are using a high contrast theme;.
        '''</summary>
        Friend Shared ReadOnly Property WarningPart_HighContrast() As String
            Get
                Return ResourceManager.GetString("WarningPart_HighContrast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} may not work correctly for the following reason(s):.
        '''</summary>
        Friend Shared ReadOnly Property WarningPart_Startup() As String
            Get
                Return ResourceManager.GetString("WarningPart_Startup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to •You are running an unsupported version of Windows;.
        '''</summary>
        Friend Shared ReadOnly Property WarningPart_UnsupportedOS() As String
            Get
                Return ResourceManager.GetString("WarningPart_UnsupportedOS", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
